import java.io.Serializable;

/**
 * 
 * @author Ayisha S.R. Sowkathali, Sifaben Vahora
 * 
 *         SetAppointment.java
 * 
 *         Class allows the user to set the appointment entered by user to the
 *         corresponding date
 *
 */
public class SetAppointment implements Serializable {

	/**
	 * serialVersionUID is generated by default to be used during deserialization to
	 * verify that the sender and receiver of a serialized object have loaded
	 * classes for that object that are compatible with respect to serialization
	 */
	private static final long serialVersionUID = 1L;

	String month;
	int year;
	int day;
	String appointment;

	public SetAppointment(String month, int year, int day, String appointment) {
		this.month = month;
		this.year = year;
		this.day = day;
		this.appointment = appointment;
	}

	@Override
	public boolean equals(Object obj) {
		SetAppointment other = (SetAppointment) obj;
		return other.month.equals(this.month) && other.year == this.year && other.day == this.day;
	}

}